name: cd

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # 코드 저장소로 부터 CI 서버로 코드를 내려받도록 워크플로우를 구성할 수 있습니다.
  checkout:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
      - run: ls -al

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          password: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd ~/Emotions/ && git stash && git pull origin main
            ./deploy.sh
